name: FastAPI CI/CD Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - develop

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13.2
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements/base.txt

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13.2
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements/base.txt

      - name: Run Ruff
        run: ruff check --output-format=github

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: [setup, lint]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13.2
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r requirements/test.txt

      - name: Run unit tests
        run: pytest --disable-warnings --maxfail=1 --cov=app
